-- Create table for survey responses
-- Drop existing table if it exists to ensure clean schema update
DROP TABLE IF EXISTS encuestas;

CREATE TABLE encuestas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Contact Information
  nombre TEXT,
  celular TEXT,
  email TEXT,
  
  -- Survey Questions
  calificacion_atencion INTEGER CHECK (calificacion_atencion >= 1 AND calificacion_atencion <= 5), -- 1. Atencion medica
  calificacion_empatia INTEGER CHECK (calificacion_empatia >= 1 AND calificacion_empatia <= 5), -- 2. Empatia personal
  claridad_informacion TEXT CHECK (claridad_informacion IN ('Sí', 'No')), -- 3. Explicacion clara
  calificacion_agendamiento INTEGER CHECK (calificacion_agendamiento >= 1 AND calificacion_agendamiento <= 5), -- 4. Proceso agendar
  tiempo_espera TEXT, -- 5. Tiempo espera (Opciones)
  calificacion_ubicacion INTEGER CHECK (calificacion_ubicacion >= 1 AND calificacion_ubicacion <= 5), -- 6. Ubicacion (Antes instalaciones)
  calificacion_limpieza INTEGER CHECK (calificacion_limpieza >= 1 AND calificacion_limpieza <= 5), -- 7. Limpieza
  calificacion_sala_espera INTEGER CHECK (calificacion_sala_espera >= 1 AND calificacion_sala_espera <= 5), -- 8. Sala espera
  red_social TEXT, -- 9. Red social
  recomendacion INTEGER CHECK (recomendacion >= 1 AND recomendacion <= 5), -- 10. Recomendar
  sugerencias TEXT -- 11. Sugerencias
);

-- Enable RLS
ALTER TABLE encuestas ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public insert (anyone can submit a survey)
CREATE POLICY "Public insert survey" ON encuestas
  FOR INSERT
  WITH CHECK (true);

-- Policy: Allow admin to read all
CREATE POLICY "Admin select survey" ON encuestas
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Policy: Allow admin to delete
CREATE POLICY "Admin delete survey" ON encuestas
  FOR DELETE
  USING (auth.role() = 'authenticated');
