-- Create table for survey responses
CREATE TABLE IF NOT EXISTS encuestas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT,
  email TEXT,
  calificacion INTEGER CHECK (calificacion >= 1 AND calificacion <= 5),
  comentario TEXT
);

-- Enable RLS
ALTER TABLE encuestas ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public insert (anyone can submit a survey)
CREATE POLICY "Public insert survey" ON encuestas
  FOR INSERT
  WITH CHECK (true);

-- Policy: Allow admin to read all (authenticated users or specific logic)
-- For simplicity in this context, we allow authenticated users (admin) to read
CREATE POLICY "Admin select survey" ON encuestas
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- Policy: Allow admin to delete
CREATE POLICY "Admin delete survey" ON encuestas
  FOR DELETE
  USING (auth.role() = 'authenticated');

